-- CreateEnum
CREATE TYPE "ApplicationDecisionSource" AS ENUM ('CANDIDATE_WITHDREW', 'PRACTICE_ACCEPTED', 'PRACTICE_REJECTED', 'ANOTHER_CANDIDATE_SELECTED', 'LISTING_CLOSED', 'LISTING_CLOSED_NO_CANDIDATE', 'LISTING_CANCELLED', 'LISTING_ERASED', 'CANDIDATE_UNAVAILABLE');

-- AlterEnum
ALTER TYPE "ListingStatus" ADD VALUE 'CLOSED_NO_CANDIDATE';

-- AlterTable
ALTER TABLE "application" ADD COLUMN     "decisionSource" "ApplicationDecisionSource";
